#!/bin/bash

# Gestion de la luminosité de l'écran
get_current_brightness() {
	current_brightness=$(brightnessctl get)
  echo "$((100*$current_brightness / 509))"
}

case "$1" in
	up)
		brightnessctl set 5%+
		display=$(get_current_brightness)
		notify-send -h int:value:"$display" -r 4321 "LUMINOSITE" -u low -t 2000
	;;
	down)
		brightnessctl set 5%-
		display=$(get_current_brightness)
		notify-send -h int:value:"$display" -r 4321 "LUMINOSITE" -u low -t 2000
	;;
	*)
		echo "Usage: $0 {up|down}"
		exit 1
		;;
esac
